/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IrRadioBtn {
    }
}
declare global {
    interface HTMLIrRadioBtnElement extends Components.IrRadioBtn, HTMLStencilElement {
    }
    var HTMLIrRadioBtnElement: {
        prototype: HTMLIrRadioBtnElement;
        new (): HTMLIrRadioBtnElement;
    };
    interface HTMLElementTagNameMap {
        "ir-radio-btn": HTMLIrRadioBtnElement;
    }
}
declare namespace LocalJSX {
    interface IrRadioBtn {
    }
    interface IntrinsicElements {
        "ir-radio-btn": IrRadioBtn;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ir-radio-btn": LocalJSX.IrRadioBtn & JSXBase.HTMLAttributes<HTMLIrRadioBtnElement>;
        }
    }
}
